apiVersion: cnat.subh.org.kube/v1alpha1
kind: At
metadata:
  labels:
    app.kubernetes.io/name: at
    app.kubernetes.io/instance: at-sample
    app.kubernetes.io/part-of: kubebuilder
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubebuilder
  name: at-sample
spec:
  command: "ls"
  schedule: "now"
